# Generated by Django 5.1.3 on 2025-01-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje_mtto', models.IntegerField()),
                ('fecha_mtto', models.DateField()),
                ('servicio_realizado', models.CharField(choices=[('SM1', 'SM1'), ('SM2', 'SM2'), ('SM3', 'SM3'), ('SM4', 'SM4')], max_length=3)),
                ('respaldo_mtto', models.FileField(blank=True, null=True, upload_to='mantenimientos/')),
                ('proximo_mantenimiento_km', models.IntegerField()),
                ('proximo_servicio', models.CharField(choices=[('SM1', 'SM1'), ('SM2', 'SM2'), ('SM3', 'SM3'), ('SM4', 'SM4')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('nro_motor', models.CharField(max_length=50)),
                ('nro_chasis', models.CharField(max_length=50)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('nro_pallets', models.IntegerField()),
                ('tipo_carroceria', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=50)),
                ('ubicacion_fisica', models.CharField(max_length=100)),
                ('propietario', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('operacion', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=100)),
                ('transportista', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('kilometraje_mtto', models.IntegerField()),
                ('servicio_realizado', models.CharField(choices=[('SM1', 'SM1'), ('SM2', 'SM2'), ('SM3', 'SM3'), ('SM4', 'SM4')], max_length=3)),
                ('respaldo_mtto', models.FileField(blank=True, null=True, upload_to='historial_mantenimientos/')),
                ('proximo_mantenimiento_km', models.IntegerField()),
                ('proximo_servicio', models.CharField(choices=[('SM1', 'SM1'), ('SM2', 'SM2'), ('SM3', 'SM3'), ('SM4', 'SM4')], max_length=3)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.mantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.vehiculo'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mantencion_Preventiva', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_vencimiento_mantencion', models.DateField(blank=True, null=True)),
                ('Revision_Tecnica', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_vencimiento_revision', models.DateField(blank=True, null=True)),
                ('Permiso_Circulacion', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_vencimiento_permiso', models.DateField(blank=True, null=True)),
                ('SOAP', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_vencimiento_soap', models.DateField(blank=True, null=True)),
                ('Padron', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_vencimiento_padron', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.vehiculo')),
            ],
        ),
    ]
