# Generated by Django 5.1.3 on 2025-01-12 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mantenimiento_vehiculo_historialmantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.vehiculo'),
        ),
    ]
