# Generated by Django 5.1.3 on 2025-01-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_mantenimiento_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallazgo', models.CharField(max_length=255)),
                ('posicion_neumatico', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8'), ('P9', 'P9'), ('P10', 'P10')], max_length=3)),
                ('fecha_inspeccion', models.DateField()),
                ('tipo_hallazgo', models.CharField(choices=[('Neumático', 'Neumático'), ('Surco', 'Surco')], max_length=50)),
                ('nivel_riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('estado_cierre', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=10)),
                ('descripcion_cierre', models.TextField(blank=True, null=True)),
                ('evidencia_cierre', models.FileField(blank=True, null=True, upload_to='cierres/')),
                ('documento_cierre', models.FileField(blank=True, null=True, upload_to='documentos_cierre/')),
                ('mensaje_confirmacion_cierre', models.TextField(blank=True, help_text='Mensaje de confirmación cuando el cierre es aprobado', null=True)),
                ('mensaje_reenvio_datos', models.TextField(blank=True, help_text='Mensaje solicitando el reenvío de datos faltantes o no comprobables', null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.group')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responsable_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_cierre', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.vehiculo')),
            ],
        ),
    ]
