# Generated by Django 5.1.3 on 2025-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_hallazgo_mensaje_confirmacion_cierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('No Disponible', 'No Disponible'), ('En Taller', 'En Taller'), ('En Venta', 'En Venta'), ('Fuera de Servicio', 'Fuera de Servicio')], max_length=50),
        ),
    ]
