# Generated by Django 5.1.3 on 2025-01-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_procedimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='App.group')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vehiculo')),
            ],
        ),
    ]
