# Generated by Django 5.1.3 on 2025-01-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_asignacionvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.group'),
        ),
        migrations.DeleteModel(
            name='Taller',
        ),
    ]
