# Generated by Django 5.1.3 on 2025-01-20 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_asignacionvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionvehiculo',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
