# Generated by Django 5.1.3 on 2025-01-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_reparacion_taller_delete_taller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionVehiculo',
        ),
    ]
