# Generated by Django 5.1.3 on 2025-01-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_asignacion_respuestaasignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaasignacion',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='respuestaasignacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='RespuestaAsignacion',
        ),
    ]
