# Generated by Django 5.1.3 on 2025-01-22 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_respuestaasignacion_taller_fecha_retiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAceptada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Reparada', 'Reparada')], default='Pendiente', max_length=20)),
                ('fecha_retiro', models.DateField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('registro', models.FileField(blank=True, null=True, upload_to='ot_reparacion/')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.vehiculo')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.group')),
            ],
            options={
                'verbose_name_plural': 'Unidades Aceptadas',
                'ordering': ['fecha_respuesta'],
            },
        ),
    ]
