# Generated by Django 5.1.3 on 2025-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255, unique=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('odometro', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
