# Generated by Django 5.1.3 on 2025-01-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_vehiculoapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoapi',
            name='identificador',
            field=models.CharField(max_length=255),
        ),
    ]
