# Generated by Django 5.1.3 on 2025-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_usuarioempresa_usuariotaller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombre_propietario',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='seccion',
        ),
    ]
