# Generated by Django 5.1.3 on 2025-01-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_canal_remove_propietario_nombre_propietario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Seccion',
            new_name='seccion',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.canal'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.marca'),
        ),
    ]
