# Generated by Django 5.1.3 on 2025-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_tipo_vehiculo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
