# Generated by Django 5.1.3 on 2025-01-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_imagendocumentos_historicaldocumento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Sin GPS', 'Sin GPS'), ('Pendiente Instalación', 'Pendiente Instalación'), ('Instalado', 'Instalado')], default='Sin GPS', max_length=30)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_gps', to='App.vehiculo')),
            ],
        ),
    ]
