# Generated by Django 5.1.3 on 2025-01-27 14:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_historicalestadogps'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallazgoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallazgo', models.CharField(max_length=255)),
                ('posicion_neumatico', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8'), ('P9', 'P9'), ('P10', 'P10')], max_length=50)),
                ('fecha_inspeccion', models.DateField()),
                ('tipo_hallazgo', models.CharField(choices=[('Neumático', 'Neumático'), ('Surco', 'Surco')], max_length=50)),
                ('nivel_riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.group')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.usuarioempresa')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_cierre', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=10)),
                ('descripcion_cierre', models.TextField(blank=True, null=True)),
                ('evidencia_cierre', models.FileField(blank=True, null=True, upload_to='cierres/')),
                ('documento_cierre', models.FileField(blank=True, null=True, upload_to='documentos_cierre/')),
                ('responsable_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_cierre', to='App.usuarioempresa')),
                ('hallazgo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.hallazgoempresa')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalHallazgoEmpresa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hallazgo', models.CharField(max_length=255)),
                ('posicion_neumatico', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8'), ('P9', 'P9'), ('P10', 'P10')], max_length=50)),
                ('fecha_inspeccion', models.DateField()),
                ('tipo_hallazgo', models.CharField(choices=[('Neumático', 'Neumático'), ('Surco', 'Surco')], max_length=50)),
                ('nivel_riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10)),
                ('evidencia', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('grupo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.usuarioempresa')),
                ('vehiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.vehiculo')),
            ],
            options={
                'verbose_name': 'historical hallazgo empresa',
                'verbose_name_plural': 'historical hallazgo empresas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
