# Generated by Django 5.1.3 on 2025-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_usuariotaller_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierre',
            name='estado_cierre',
        ),
        migrations.AddField(
            model_name='hallazgoempresa',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalhallazgoempresa',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=10),
        ),
    ]
