# Generated by Django 5.1.3 on 2025-01-29 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.group'),
        ),
        migrations.AlterField(
            model_name='historicalvehiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='App.group'),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
