# Generated by Django 5.1.3 on 2025-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_hallazgoempresa_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tipo_grupo',
            field=models.CharField(choices=[('taller', 'Taller'), ('empresa', 'Empresa')], default='taller', max_length=10),
        ),
    ]
