# Generated by Django 5.1.3 on 2025-02-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_group_tipo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_taller',
            name='descripcion_asignacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion_taller',
            name='descripcion_tarea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion_taller',
            name='empresa_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='App.group'),
        ),
        migrations.AddField(
            model_name='asignacion_taller',
            name='fecha_disponible_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion_taller',
            name='fecha_disponible_mantencion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion_taller',
            name='tipo',
            field=models.CharField(choices=[('mantencion_preventiva', 'Mantención Preventiva'), ('mantencion_correctiva', 'Mantención Correctiva'), ('reparacion', 'Reparación'), ('asignacion_empresa', 'Asignación Empresa')], default='Mantención Preventiva', max_length=30),
        ),
        migrations.AlterField(
            model_name='asignacion_taller',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='App.group'),
        ),
    ]
