# Generated by Django 5.1.3 on 2025-02-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_asignacion_taller_descripcion_asignacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.group')),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='licencias/%Y/%m/%d/')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='App.conductor')),
            ],
        ),
    ]
