# Generated by Django 5.1.3 on 2025-02-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_conductor_licenciaconductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoapi',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_data', to='App.vehiculo'),
        ),
    ]
