# Generated by Django 5.1.3 on 2025-02-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_alter_hallazgoempresa_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallazgoempresa',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.usuarioempresa'),
        ),
    ]
